version: '3'
services:
  cait_broker:
    network_mode: host
    image: "cortictech/broker:0.51"
    restart: always 
    command: "bash /start_broker.sh"

  cait_homeassistant:
    network_mode: host
    privileged: true
    image: "homeassistant/home-assistant:stable"
    environment:
      - TZ=America/Vancouver
    volumes:
      - /home/pi/homeassistant/config/:/config
    ports:
      - 8123:8123
  
  cait_nlp:
    network_mode: host
    image: "cortictech/nlp:0.51"
    restart: always 
    volumes:
      - /opt/cortic_modules/nlp_module:/nlp_module
    command: "taskset --cpu-list 2 python3 /nlp_module/nlu.py"
  
  cait_stt_tts:
    network_mode: host
    privileged: true
    image: "cortictech/speech:0.51"
    restart: always 
    # environment:
    #   - PULSE_SERVER=unix:/tmp/pulseaudio.socket
    #   - PULSE_COOKIE=/tmp/pulseaudio.cookie
    volumes:
      - /sys/bus/usb:/sys/bus/usb
      - /dev/bus/usb:/dev/bus/usb
      - /dev/snd:/dev/snd
      - /opt/cortic_modules/voice_module:/voice_module
    #   - /tmp/pulseaudio.socket:/tmp/pulseaudio.socket
    #   - /opt/pulseaudio.client.conf:/etc/pulse/client.conf
    user: root
    command: 'bash /voice_module/start.sh'

  cait_vision:
    network_mode: host
    privileged: true
    image: "cortictech/vision:0.51"
    restart: always 
    volumes:
      - /lib/modules:/lib/modules
      - /dev:/dev
      - /opt/cortic_modules/vision_module:/vision_module
    user: root
    command: "bash /vision_module/start.sh"

  cait_control:
    network_mode: host
    privileged: true
    image: "cortictech/control:0.51"
    restart: always 
    volumes:
      - /opt/cortic_modules/control_module:/control_module
    command: "python3.5 /control_module/control.py"
    
